# -*- coding: utf-8 -*-
"""train_model

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NDzkXP6UsR7Wb1PsgRMEzHlqzdu9sFBY
"""

import os
import joblib
from preprocess import prepare_data,perform_clustering
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

df_full, df_scaled, df_cleaned=prepare_data("BankChurners.csv")
cluster_labels=perform_clustering(df_scaled)
df_scaled['Cluster'] = cluster_labels
X = df_scaled.drop(columns=['Cluster'])
y = df_scaled['Cluster']

"""Decision Tree"""

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

dt = DecisionTreeClassifier(max_depth=3, random_state=42)
dt.fit(X_train, y_train)
y_pred = dt.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display a classification report
print(classification_report(y_test, y_pred))

# Save model
model_dir = 'models/question_5'
os.makedirs(model_dir, exist_ok=True)
model_path = os.path.join(model_dir, 'dt.pkl')

joblib.dump(dt, model_path)
print(f"Model saved to {model_path}")

"""Random Forest"""

rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)

# Make predictions
y_pred = rf.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display a classification report
print(classification_report(y_test, y_pred))

# Save model
model_dir = 'models/question_5'
os.makedirs(model_dir, exist_ok=True)
model_path = os.path.join(model_dir, 'rf.pkl')

joblib.dump(rf, model_path)
print(f"Model saved to {model_path}")

"""XGBoost"""

from xgboost import XGBClassifier

xgb = XGBClassifier(n_estimators=100, learning_rate=0.1)
xgb.fit(X_train, y_train)
y_pred = xgb.predict(X_test)

accuracy = accuracy_score(y_test, y_pred)
print(f'Accuracy: {accuracy:.2f}')

# Display a classification report
print(classification_report(y_test, y_pred))

# Save model
model_dir = 'models/question_5'
os.makedirs(model_dir, exist_ok=True)
model_path = os.path.join(model_dir, 'xgb.pkl')

joblib.dump(xgb, model_path)
print(f"Model saved to {model_path}")
