# -*- coding: utf-8 -*-
"""subB_data_preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1usv_gkisFmUb732AbMuSjzF56HLoZd8e
"""

import pandas as pd
import numpy as np
import os
from sklearn.preprocessing import LabelEncoder, StandardScaler, OrdinalEncoder

os.chdir(os.path.dirname(os.path.abspath(__file__)))

# Import data - fixing the training data reading issues
banking_marketing_train = pd.read_csv('synthesized/synthesized_train.csv')
banking_marketing_test = pd.read_csv('synthesized/synthesized_test.csv')

# Create copies for encoded data
banking_marketing_train_encoded = banking_marketing_train.copy()
banking_marketing_test_encoded = banking_marketing_test.copy()

# Numeric columns
numeric_columns = ['age','balance','day','duration','campaign','pdays','previous','deposit_amount']
numeric_columns = [col for col in numeric_columns if col in banking_marketing_train.columns]

scaler = StandardScaler()
for col in numeric_columns:
    banking_marketing_train_encoded[col] = scaler.fit_transform(banking_marketing_train[col].values.reshape(-1, 1)).flatten()
    banking_marketing_test_encoded[col] = scaler.transform(banking_marketing_test[col].values.reshape(-1, 1)).flatten()

# Binary columns (yes/no)
binary_columns = ['default','housing','loan','y']
binary_columns = [col for col in binary_columns if col in banking_marketing_train.columns]

for column in binary_columns:
    banking_marketing_train_encoded[column] = banking_marketing_train[column].map({'yes': 1, 'no': 0})
    banking_marketing_test_encoded[column] = banking_marketing_test[column].map({'yes': 1, 'no': 0})

# Nominal columns (one-hot encoding)
nominal_columns = ['job','marital','contact','poutcome']
nominal_columns = [col for col in nominal_columns if col in banking_marketing_train.columns]

if nominal_columns:
    banking_marketing_train_encoded = pd.get_dummies(banking_marketing_train_encoded, columns=nominal_columns)
    banking_marketing_test_encoded = pd.get_dummies(banking_marketing_test_encoded, columns=nominal_columns)
encoder = LabelEncoder()
for col in nominal_columns:
        banking_marketing_train_encoded[col] = encoder.fit_transform(banking_marketing_train[col])
        banking_marketing_test_encoded[col] = encoder.transform(banking_marketing_test[col])

# Ordinal columns (label encoding)
ordinal_columns = ['education','month']
ordinal_columns = [col for col in ordinal_columns if col in banking_marketing_train.columns]

if ordinal_columns:
    encoder = LabelEncoder()
    for col in ordinal_columns:
        banking_marketing_train_encoded[col] = encoder.fit_transform(banking_marketing_train[col])
        banking_marketing_test_encoded[col] = encoder.transform(banking_marketing_test[col])

deposit_products=["current","three_months","six_months","one_year","two_year"]
ordinal_encoder = OrdinalEncoder(categories=[deposit_products])
banking_marketing_train_encoded['term'] = ordinal_encoder.fit_transform(banking_marketing_train[['term']]).flatten()
banking_marketing_test_encoded['term'] = ordinal_encoder.transform(banking_marketing_test[['term']]).flatten()

# Create cost column
if all(col in banking_marketing_train_encoded.columns for col in ['duration', 'campaign']):
    banking_marketing_train_encoded['cost'] = banking_marketing_train_encoded['duration'] * banking_marketing_train_encoded['campaign'] / 3600 * 38
    banking_marketing_test_encoded['cost'] = banking_marketing_test_encoded['duration'] * banking_marketing_test_encoded['campaign'] / 3600 * 38

# [Rest of your feature engineering code...]
# Include the CLV, conversion rate, contact time, and fatigue score calculations here
# Make sure to add similar existence checks for all columns being used

# Save processed data
banking_marketing_train_encoded.to_csv('processed/banking_marketing_train_processed.csv', index=False)
banking_marketing_test_encoded.to_csv('processed/banking_marketing_test_processed.csv', index=False)
