# -*- coding: utf-8 -*-
"""preprocess.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jz0KI5ko6U9Ss5WkpDoZaCyH13r2o3XX
"""

import pandas as pd
import numpy as np
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.cluster import KMeans
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score, classification_report

# Load Data (Replace with actual file path if needed)
df = pd.read_csv("banking_marketing_train_processed.csv")

# --------------------------------------------
# Customer Segmentation
# --------------------------------------------

# Encode Categorical Features
categorical_cols = df.select_dtypes(include=['object']).columns.tolist()
if categorical_cols:
    for col in categorical_cols:
        df[col] = LabelEncoder().fit_transform(df[col])

# Normalize Numerical Features
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=['int64', 'float64']).columns.tolist()
df[numeric_cols] = scaler.fit_transform(df[numeric_cols])

# Perform K-Means Clustering (5 Segments)
kmeans = KMeans(n_clusters=5, random_state=42, n_init=10)
df['Cluster'] = kmeans.fit_predict(df[numeric_cols])

# Define customer segment descriptions
cluster_mapping = {
    0: "Mid-High Income Males with Dependents, Strong Banking Relationship",
    1: "Young, Low-Income Females with Shortest Tenure & Low Credit",
    2: "Older, Low-Income Females with Strong Banking Relationship & High Utilisation",
    3: "Mid-Income Graduates with High Spending & Transactions",
    4: "Educated, Single Individuals with High Credit & Low Utilisation"
}

# Map clusters to descriptions
df['customer_segment'] = df['Cluster'].map(cluster_mapping)

# --------------------------------------------
# Train Models to Predict Customer Segments
# --------------------------------------------

X = df.drop(columns=['Cluster', 'customer_segment'])
y = df['Cluster']

# Train-test split (80-20)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train Decision Tree Classifier
dt = DecisionTreeClassifier(max_depth=3, random_state=42)
dt.fit(X_train, y_train)
y_pred_dt = dt.predict(X_test)
print(f"\nDecision Tree Accuracy: {accuracy_score(y_test, y_pred_dt):.2f}")
print(classification_report(y_test, y_pred_dt))

# Train Random Forest Classifier
rf = RandomForestClassifier(n_estimators=100, random_state=42)
rf.fit(X_train, y_train)
y_pred_rf = rf.predict(X_test)
print(f"\nRandom Forest Accuracy: {accuracy_score(y_test, y_pred_rf):.2f}")
print(classification_report(y_test, y_pred_rf))

# Train XGBoost Classifier
xgb = XGBClassifier(n_estimators=100, learning_rate=0.1, random_state=42)
xgb.fit(X_train, y_train)
y_pred_xgb = xgb.predict(X_test)
print(f"\nXGBoost Accuracy: {accuracy_score(y_test, y_pred_xgb):.2f}")
print(classification_report(y_test, y_pred_xgb))

# --------------------------------------------
# Apply Best Model (XGBoost) to Full Dataset
# --------------------------------------------

df['Predicted_Segment'] = xgb.predict(X)
df['customer_segment'] = df['Predicted_Segment'].map(cluster_mapping)

# Save the entire dataset with segmentation
df.to_csv("customer_segments_full.csv", index=False)

print("Customer Segmentation Completed & Full Dataset Saved!")